### ISSUE TITLE
Running SPARQL10ManifestTest.java

### ISSUE THREAD

**Issue by D063520** [eclipse/rdf4j-testsuite#24]
Hello,

I feel quite stupid asking this question, but I just would like to run the:

SPARQL10ManifestTest

against my own implementation of org.eclipse.rdf4j.repository.Repository. I can run queries on my Repository after opening a RepositoryConnection. But somehow I'm not able to use the SPARQL10ManifestTest.java class to run the tests contained in the corresponding manifest file. I'm stuck in implementing the SPARQLQueryTest.Factory. Could you share some code for that?

Thank you
D063520

**Comment by jeenbroekstra** [comment]
Sure! Have a look at https://github.com/eclipse/rdf4j-tools/blob/master/compliance/sparql/src/test/java/org/eclipse/rdf4j/query/parser/sparql/manifest/W3CApprovedSPARQL10QueryTest.java . It implements an anonymous subclass of this factory, and shows how to tie in the test suite with a particular repo. 

Though to be fair, unless you've also completely re-implemented the SPARQL engine in your repo implementation, it might be better to just run compliance tests by extending/implementing the testsuite classes in `rdf4j-store-testsuite`, in particular https://github.com/eclipse/rdf4j-testsuite/blob/master/store/src/main/java/org/eclipse/rdf4j/repository/RepositoryConnectionTest.java . This ensures that your repo implementation conforms to the API specifications. SPARQL query compliance is handled by a separate RDF4J component, so if your repository impl delegates query processing to that component, and your repo conforms to the api specs/tests, you have a solid assurance that you're SPARQL-compliant as well.

**Comment by jeenbroekstra** [comment]
As an aside, happy to help you here of course but we prefer to use our google group (https://groups.google.com/d/forum/rdf4j-users) for community support, and reserve github issues for bugs reports and feature requests only.
